package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     /**
	 * 
	 */
	 private Integer idalumno;
     private Persona persona;
     private Set informaciondetalles = new HashSet(0);
     private Set cursoFavoritos = new HashSet(0);

    public Alumno() {
    }

    public Alumno(Persona persona, Set informaciondetalles, Set cursoFavoritos) {
       this.persona = persona;
       this.informaciondetalles = informaciondetalles;
       this.cursoFavoritos = cursoFavoritos;
    }
   
    public Integer getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(Integer idalumno) {
        this.idalumno = idalumno;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getInformaciondetalles() {
        return this.informaciondetalles;
    }
    
    public void setInformaciondetalles(Set informaciondetalles) {
        this.informaciondetalles = informaciondetalles;
    }
    public Set getCursoFavoritos() {
        return this.cursoFavoritos;
    }
    
    public void setCursoFavoritos(Set cursoFavoritos) {
        this.cursoFavoritos = cursoFavoritos;
    }

	@Override
	public String toString() {
		return "Alumno [idalumno=" + idalumno + ", persona=" + persona 
				+ "]";
	}

}


