package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {



	private Integer idcategoria;
     private String nombrecategoria;
     private Set cursos = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nombrecategoria, Set cursos) {
       this.nombrecategoria = nombrecategoria;
       this.cursos = cursos;
    }
   
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombrecategoria() {
        return this.nombrecategoria;
    }
    
    public void setNombrecategoria(String nombrecategoria) {
        this.nombrecategoria = nombrecategoria;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }



    @Override
	public String toString() {
		return "Categoria [idcategoria=" + idcategoria + ", nombrecategoria=" + nombrecategoria +  "]";
	}

}


