package dao.entidad;

import java.util.Date;

// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer idcomentario;
     private CursoXDocente cursoXDocente;
     private String comentario;
     private String usuario;
     private Date fecha;
     
    public Comentario() {
    }

    public Comentario(CursoXDocente cursoXDocente) {
       this.cursoXDocente = cursoXDocente;
    }
   
    public Integer getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(Integer idcomentario) {
        this.idcomentario = idcomentario;
    }
    public CursoXDocente getCursoXDocente() {
        return this.cursoXDocente;
    }
    
    public void setCursoXDocente(CursoXDocente cursoXDocente) {
        this.cursoXDocente = cursoXDocente;
    }

	public String getComentario() {
		return comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

    

}


