package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1



/**
 * CursoXDocenteId generated by hbm2java
 */
public class CursoXDocenteId  implements java.io.Serializable {


     private int idcurDoc;
     private int idcurso;
     private int iddocente;

    public CursoXDocenteId() {
    }

    public CursoXDocenteId(int idcurDoc, int idcurso, int iddocente) {
       this.idcurDoc = idcurDoc;
       this.idcurso = idcurso;
       this.iddocente = iddocente;
    }
   
    public int getIdcurDoc() {
        return this.idcurDoc;
    }
    
    public void setIdcurDoc(int idcurDoc) {
        this.idcurDoc = idcurDoc;
    }
    public int getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }
    public int getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(int iddocente) {
        this.iddocente = iddocente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CursoXDocenteId) ) return false;
		 CursoXDocenteId castOther = ( CursoXDocenteId ) other; 
         
		 return (this.getIdcurDoc()==castOther.getIdcurDoc())
 && (this.getIdcurso()==castOther.getIdcurso())
 && (this.getIddocente()==castOther.getIddocente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcurDoc();
         result = 37 * result + this.getIdcurso();
         result = 37 * result + this.getIddocente();
         return result;
   }

@Override
public String toString() {
	return "CursoXDocenteId [idcurDoc=" + idcurDoc + ", idcurso=" + idcurso + ", iddocente=" + iddocente + "]";
}
   
}


