package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1



/**
 * CursoFavoritoId generated by hbm2java
 */
public class CursoFavoritoId  implements java.io.Serializable {


     private int idcursofav;
     private int idalumno;
     private int idcurDoc;
     private int idcurso;
     private int iddocente;

    public CursoFavoritoId() {
    }

    public CursoFavoritoId(int idcursofav, int idalumno, int idcurDoc, int idcurso, int iddocente) {
       this.idcursofav = idcursofav;
       this.idalumno = idalumno;
       this.idcurDoc = idcurDoc;
       this.idcurso = idcurso;
       this.iddocente = iddocente;
    }
   
    public int getIdcursofav() {
        return this.idcursofav;
    }
    
    public void setIdcursofav(int idcursofav) {
        this.idcursofav = idcursofav;
    }
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }
    public int getIdcurDoc() {
        return this.idcurDoc;
    }
    
    public void setIdcurDoc(int idcurDoc) {
        this.idcurDoc = idcurDoc;
    }
    public int getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }
    public int getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(int iddocente) {
        this.iddocente = iddocente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CursoFavoritoId) ) return false;
		 CursoFavoritoId castOther = ( CursoFavoritoId ) other; 
         
		 return (this.getIdcursofav()==castOther.getIdcursofav())
 && (this.getIdalumno()==castOther.getIdalumno())
 && (this.getIdcurDoc()==castOther.getIdcurDoc())
 && (this.getIdcurso()==castOther.getIdcurso())
 && (this.getIddocente()==castOther.getIddocente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcursofav();
         result = 37 * result + this.getIdalumno();
         result = 37 * result + this.getIdcurDoc();
         result = 37 * result + this.getIdcurso();
         result = 37 * result + this.getIddocente();
         return result;
   }

@Override
public String toString() {
	return "CursoFavoritoId [idcursofav=" + idcursofav + ", idalumno=" + idalumno + ", idcurDoc=" + idcurDoc
			+ ", idcurso=" + idcurso + ", iddocente=" + iddocente + "]";
}   


}


