package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idcurso;
     private Categoria categoria;
     private Nivel nivel;
     private String nombre;
     private Set cursoXDocentes = new HashSet(0);
     private Set informaciondetalles = new HashSet(0);

    public Curso() {
    }

    public Curso(Categoria categoria, Nivel nivel, String nombre, Set cursoXDocentes, Set informaciondetalles) {
       this.categoria = categoria;
       this.nivel = nivel;
       this.nombre = nombre;
       this.cursoXDocentes = cursoXDocentes;
       this.informaciondetalles = informaciondetalles;
    }
   
    public Integer getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCursoXDocentes() {
        return this.cursoXDocentes;
    }
    
    public void setCursoXDocentes(Set cursoXDocentes) {
        this.cursoXDocentes = cursoXDocentes;
    }
    public Set getInformaciondetalles() {
        return this.informaciondetalles;
    }
    
    public void setInformaciondetalles(Set informaciondetalles) {
        this.informaciondetalles = informaciondetalles;
    }

	@Override
	public String toString() {
		return "Curso [idcurso=" + idcurso + ", categoria=" + categoria + ", nivel=" + nivel + ", nombre=" + nombre+"]";
	}


}


