package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer iddocente;
     private NivelEstudio nivelEstudio;
     private Persona persona;
     private String desc_biografia;
     private String carrera;
     private Set cursoXDocentes = new HashSet(0);

    public Docente() {
    }


	public Docente(NivelEstudio nivelEstudio, Persona persona, String desc_biografia, String carrera,
			Set cursoXDocentes) {
		this.nivelEstudio = nivelEstudio;
		this.persona = persona;
		this.desc_biografia = desc_biografia;
		this.carrera = carrera;
		this.cursoXDocentes = cursoXDocentes;
	}

    public Integer getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(Integer iddocente) {
        this.iddocente = iddocente;
    }
    public NivelEstudio getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(NivelEstudio nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getCursoXDocentes() {
        return this.cursoXDocentes;
    }
    
    public void setCursoXDocentes(Set cursoXDocentes) {
        this.cursoXDocentes = cursoXDocentes;
    }
    

    public String getDesc_biografia() {
		return desc_biografia;
	}

	public void setDesc_biografia(String desc_biografia) {
		this.desc_biografia = desc_biografia;
	}

	public String getCarrera() {
		return carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	@Override
	public String toString() {
		return "Docente [iddocente=" + iddocente + ", nivelEstudio=" + nivelEstudio + ", persona=" + persona
				 + "]";
	}


}


