package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;

/**
 * Informaciondetalle generated by hbm2java
 */
public class Informaciondetalle  implements java.io.Serializable {


     private InformaciondetalleId id;
     private Alumno alumno;
     private Curso curso;
     private Docente docente;
     private String infoDetalle;
     private Date fecha;

    private ArrayList<Integer> select;
    private ArrayList<Integer> noSelect;
    
    public Informaciondetalle() {
    }

	
    public Informaciondetalle(InformaciondetalleId id, Alumno alumno, Curso curso,Docente docente) {
        this.id = id;
        this.alumno = alumno;
        this.curso = curso;
        this.docente = docente;
    }
    public Informaciondetalle(InformaciondetalleId id, Alumno alumno, Curso curso,Docente docente, String infoDetalle, Date fecha) {
       this.id = id;
       this.alumno = alumno;
       this.curso = curso;
       this.docente = docente;
       this.infoDetalle = infoDetalle;
       this.fecha = fecha;
    }
   
    public InformaciondetalleId getId() {
        return this.id;
    }
    
    public void setId(InformaciondetalleId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    
    
    public Docente getDocente() {
		return docente;
	}


	public void setDocente(Docente docente) {
		this.docente = docente;
	}


	public String getInfoDetalle() {
        return this.infoDetalle;
    }
    
    public void setInfoDetalle(String infoDetalle) {
        this.infoDetalle = infoDetalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

	public ArrayList<Integer> getSelect() {
		return select;
	}

	public void setSelect(ArrayList<Integer> select) {
		this.select = select;
	}

	public ArrayList<Integer> getNoSelect() {
		return noSelect;
	}

	public void setNoSelect(ArrayList<Integer> noSelect) {
		this.noSelect = noSelect;
	}


	@Override
	public String toString() {
		return "Informaciondetalle [id=" + id + ", alumno=" + alumno + ", curso=" + curso + ", docente=" + docente
				+ ", infoDetalle=" + infoDetalle + ", fecha=" + fecha + "]";
	}

}


