package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NivelEstudio generated by hbm2java
 */
public class NivelEstudio  implements java.io.Serializable {


     private Integer idnivelestudio;
     private String nombre;
     private Set docentes = new HashSet(0);

    public NivelEstudio() {
    }

    public NivelEstudio(String nombre, Set docentes) {
       this.nombre = nombre;
       this.docentes = docentes;
    }
   
    public Integer getIdnivelestudio() {
        return this.idnivelestudio;
    }
    
    public void setIdnivelestudio(Integer idnivelestudio) {
        this.idnivelestudio = idnivelestudio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }

	@Override
	public String toString() {
		return "NivelEstudio [idnivelestudio=" + idnivelestudio + ", nombre=" + nombre + "]";
	}

}


