package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idperfil;
     private String nombreperfil;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

    public Perfil(String nombreperfil, Set usuarios) {
       this.nombreperfil = nombreperfil;
       this.usuarios = usuarios;
    }
   
    public Integer getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(Integer idperfil) {
        this.idperfil = idperfil;
    }
    public String getNombreperfil() {
        return this.nombreperfil;
    }
    
    public void setNombreperfil(String nombreperfil) {
        this.nombreperfil = nombreperfil;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

	@Override
	public String toString() {
		return "Perfil [idperfil=" + idperfil + ", nombreperfil=" + nombreperfil + ", usuarios=" + usuarios + "]";
	}




}


