package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private Integer idpersona;
	private Ubigeo ubigeo;
	private String direccion;
	private Date fechaNac;
	private String nombres;
	private String apellidos;
	private Integer telefono;
	private String correoelectronico;
	private Blob foto;
	private Set docentes = new HashSet(0);
	private Set usuarios = new HashSet(0);
	private Set alumnos = new HashSet(0);

	public Persona() {
	}

	public Persona(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	public Persona(Integer idpersona, Ubigeo ubigeo, String direccion, Date fechaNac, String nombres, String apellidos,
			Integer telefono, String correoelectronico, Blob foto, Set docentes, Set usuarios, Set alumnos) {
		this.idpersona = idpersona;
		this.ubigeo = ubigeo;
		this.direccion = direccion;
		this.fechaNac = fechaNac;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.correoelectronico = correoelectronico;
		this.foto = foto;
		this.docentes = docentes;
		this.usuarios = usuarios;
		this.alumnos = alumnos;
	}

	public Integer getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getCorreoelectronico() {
		return this.correoelectronico;
	}

	public void setCorreoelectronico(String correoelectronico) {
		this.correoelectronico = correoelectronico;
	}

	public Blob getFoto() {
		return this.foto;
	}

	public void setFoto(Blob foto) {
		this.foto = foto;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

	@Override
	public String toString() {
		return "Persona [idpersona=" + idpersona + ", ubigeo=" + ubigeo + ", direccion=" + direccion + ", fechaNac="
				+ fechaNac + ", nombres=" + nombres + ", apellidos=" + apellidos + ", telefono=" + telefono
				+ ", correoelectronico=" + correoelectronico + "]";
	}

}
