package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Perfil perfil;
     private Persona persona;
     private String password;

    public Usuario() {
    }

	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Perfil perfil, Persona persona, String password) {
       this.perfil = perfil;
       this.persona = persona;
       this.password = password;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public void setPerfil(int PERFIL_ALUMNO) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


	@Override
	public String toString() {
		return "Usuario [idusuario=" + idusuario + ", perfil=" + perfil + ", persona=" + persona + ", password="
				+ password + "]";
	}






}


