package dao.entidad;
// Generated 27/09/2016 02:04:24 PM by Hibernate Tools 4.3.1



/**
 * CursoFavorito generated by hbm2java
 */
public class ValorCursoXDocente  implements java.io.Serializable {


     private ValorCursoXDocenteId id;
     private Alumno alumno;
     private CursoXDocente cursoXDocente;
     private Integer valor;

    public ValorCursoXDocente() {
    }

    public ValorCursoXDocente(ValorCursoXDocenteId id, Alumno alumno, CursoXDocente cursoXDocente,Integer valor) {
       this.id = id;
       this.alumno = alumno;
       this.cursoXDocente = cursoXDocente;
       this.valor = valor;
    }
   
    public ValorCursoXDocenteId getId() {
		return id;
	}

	public void setId(ValorCursoXDocenteId id) {
		this.id = id;
	}

	public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public CursoXDocente getCursoXDocente() {
        return this.cursoXDocente;
    }
    
    public void setCursoXDocente(CursoXDocente cursoXDocente) {
        this.cursoXDocente = cursoXDocente;
    }

    
	public Integer getValor() {
		return valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	@Override
	public String toString() {
		return "ValorCursoXDocente [id=" + id + ", alumno=" + alumno + ", cursoXDocente=" + cursoXDocente + ", valor="
				+ valor + "]";
	}

	
}


